server:
  port: 8000
  servlet:
    context-path: /api

spring:
  application:
    name: Next.js-Antd-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nextjs_antd?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
